application/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, SelectField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    category = SelectField('Category', choices=[('P', 'Programming'), ('S', 'Science'), ('M', 'Machine Learning'), ('O', 'Other Tech')], default='O')
    submit = SubmitField('Post')

application/posts/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import current_user, login_required
from application import db
from application.models import Post, User
from application.posts.forms import PostForm

posts = Blueprint('posts', __name__)


@posts.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data,
                    content=form.content.data,
                    category=dict(form.category.choices).get(form.category.data),
                    author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.index'))
    return render_template('posts/post_form.html', title='New Post', form=form)


@posts.route('/post/<int:post_id>')
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('posts/post.html', title=post.title, post=post)


@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    form.submit.label.text = 'Update'
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        post.category = dict(form.category.choices).get(form.category.data)
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
        form.category.data = post.category[0]
    return render_template('posts/post_form.html', title='Update Post', form=form)


@posts.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.index'))


@posts.route('/post/<string:category>')
def category_posts(category):
    page = request.args.get('page', 1, type=int)
    posts = Post.query\
        .filter_by(category=category)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    print('posts', posts.items)
    if not posts.items:
        return render_template('posts/no_post.html', category=category)
    users = [User.query\
        .filter(User.posts.contains(post))
        .all() for post in posts.items]
    print('users', users)
    return render_template('posts/category_posts.html', posts=posts, users=users)

application/users/routes.py
import os
import asyncio
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from application import db, bcrypt
from application.models import User, Post
from application.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, ResetRequestForm, ResetPasswordForm
from application.users.utils import save_picture, remove_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = RegistrationForm()

    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user = User(username=form.username.data,
                    email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('You account has been created! You are now able to log in.', 'success')
        return redirect(url_for('users.login'))

    return render_template('users/register.html', title='Register', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.index'))
        flash('Login unsuccessful. Please check email and password.', 'danger')
    return render_template('users/login.html', title='Login', form=form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.index'))


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            remove_picture(current_user.image_file)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('You account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for(
        'static', filename='profile_pics/' + current_user.image_file)
    return render_template('users/account.html', title='Account', image_file=image_file, form=form)


@users.route('/user/<string:username>')
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query\
        .filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('users/user_posts.html', posts=posts, user=user)


@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = ResetRequestForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent to you containing a link to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('users/reset_request.html', title='Reset Password', form=form)


@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    user = User.verify_reset_token(token)
    if not user:
        flash('Token is invalid or expired.', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('You password has been updated! You are now able to log in.', 'success')
        return redirect(url_for('users.login'))
    return render_template('users/reset_token.html', title='Reset Password', form=form)

application/templates/index.html
{% extends 'layout.html' %}

{% block content %}
    {% for post in posts.items %}
        <div class="card mb-3 p-3 shadow bg-light">
            <div class="row">
                <div class="ml-3 mb-3 pr-2">
                    <img src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}" class="post-img rounded mx-md-auto d-block">
                </div>
                <div class="col">
                    <h6 class="post-category mb-1 small">
                        {% filter upper %}
                            {{ post.category}}
                        {% endfilter %}
                    </h6>
                    <h3 class="post-title mb-3">
                        <a class="clean-a" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a>
                    </h3>
                    <div class="text-muted small mb-3">
                        By <a class="clean-a" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                        on {{ post.date_posted.strftime('%b %d, %Y')}}
                    </div>
                    <p class="post-content">{{ post.content }}</p>
                </div>
            </div>
        </div>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if page_num == posts.page %}
                <a href="{{ url_for('main.index', page=page_num) }}" class="btn btn-info mb-4">{{ page_num }}</a>
            {% else %}
                <a href="{{ url_for('main.index', page=page_num) }}" class="btn btn-outline-info mb-4">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
{% endblock %}

application/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    {% set active_page = active_page|default('index') %}
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top mb-5">
            <div class="container">
                <a class="navbar-brand" href="{{ url_for('main.index') }}">MyFlaskJournal</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ml-auto">
                        {% if current_user.is_authenticated %}
                            <li {% if active_page == 'new_post' %} class="active nav-item" {% else %} class="nav-item" {% endif %}>
                                <a class="nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
                            </li>
                            <li {% if active_page == 'account' %} class="active nav-item" {% else %} class="nav-item" {% endif %}>
                                <a class="nav-link" href="{{ url_for('users.account') }}">Account</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                            </li>                        
                        {% else %}
                            <li {% if active_page == 'login' %} class="active nav-item" {% else %} class="nav-item" {% endif %}>
                                <a class="nav-link" href="{{ url_for('users.login') }}">Login</a>
                            </li>
                            <li {% if active_page == 'register' %} class="active nav-item" {% else %} class="nav-item" {% endif %}>
                                <a class="nav-link" href="{{ url_for('users.register') }}">Register</a>
                            </li>
                        {% endif %}                    
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <br>
    <main role="main" class="container mt-5">
        <div class="row">
            <div class="col-md-8">
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }}">
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
                {% block content %}{% endblock %}
            </div>
            <div class="col-md-4">
                <div class="rounded bg-light shadow px-4 py-3 border">
                    <h3>Categories</h3>
                    <p class='text-muted'>View by your favourite category
                        <ul class="list-group">
                            <a href="{{ url_for('posts.category_posts', category='Programming') }}" class="clean-a">
                                <li {% if active_page == 'Programming' %} class="list-group-item list-group-item-light border-info" {% else %} class="list-group-item list-group-item-light" {% endif %}>
                                    Programming
                                </li>
                            </a>
                            <a href="{{ url_for('posts.category_posts', category='Science') }}" class="clean-a">
                                <li {% if active_page == 'Science' %} class="list-group-item list-group-item-light border-info" {% else %} class="list-group-item list-group-item-light" {% endif %}>
                                    Science
                                </li>
                            </a>
                            <a href="{{ url_for('posts.category_posts', category='Machine Learning') }}" class="clean-a">
                                <li {% if active_page == 'Machine Learning' %} class="list-group-item list-group-item-light border-info" {% else %} class="list-group-item list-group-item-light" {% endif %}>
                                    Machine Learning
                                </li>
                            </a>
                            <a href="{{ url_for('posts.category_posts', category='Other Tech') }}" class="clean-a">
                                <li {% if active_page == 'Other Tech' %} class="list-group-item list-group-item-light border-info" {% else %} class="list-group-item list-group-item-light" {% endif %}>
                                    Other Tech
                                </li>
                            </a>
                        </ul>
                    </p>
                </div>
            </div>
        </div>
    </main>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

application/templates/post.html
{% extends 'layout.html' %}

{% block content %}
    {% if post.author == current_user %}
        <div class="mb-3">
            <a href="{{ url_for('posts.update_post', post_id=post.id) }}" class="btn btn-md btn-secondary mr-3">Update</a>
            <button class="btn btn-danger btn-md" data-toggle="modal" data-target="#deleteModal">Delete</button>
        </div>
    {% endif %}
    <div class="card mb-3 p-3 shadow bg-light">
            <div class="row">
                <div class="ml-3 mb-3 pr-2">
                    <img src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}" class="post-img rounded mx-md-auto d-block">
                </div>
                <div class="col">
                    <h6 class="post-category mb-1 small">
                        {% filter upper %}
                            {{ post.category}}
                        {% endfilter %}
                    </h6>
                    <h3 class="post-title mb-3">
                        <a class="clean-a" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a>
                    </h3>
                    <div class="text-muted small mb-3">
                        By <a class="clean-a" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                        on {{ post.date_posted.strftime('%b %d, %Y')}}
                    </div>
                    <p class="post-content">{{ post.content }}</p>
                </div>
            </div>
        </div>
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Delete">
                </form>
            </div>
            </div>
        </div>
    </div>
{% endblock %}

application/templates/user_posts.html
{% extends 'layout.html' %}

{% block content %}
    <h1 class="mb-3">Posts by {{ user.username }} ({{ posts.total }})</h1>
    {% for post in posts.items %}
        <div class="card mb-3 p-3 shadow bg-light">
            <div class="row">
                <div class="ml-3 mb-3 pr-2">
                    <img src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}" class="post-img rounded mx-md-auto d-block">
                </div>
                <div class="col">
                    <h6 class="mb-2 text-muted small">{{ post.date_posted.strftime('%A, %d %B %Y')}}</h6>
                    <hr class="my-2">
                    <h4 class="post-title">
                        <a class="clean-a" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a>
                    </h4>
                    <div class="text-muted small mb-3">
                        <a class="clean-a" href="{{ url_for('users.user_posts', username=post.author.username) }}">By {{ post.author.username }}</a>
                    </div>
                    <p class="post-content">{{ post.content }}</p>
                </div>
            </div>
        </div>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if page_num == posts.page %}
                <a href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}" class="btn btn-info mb-4">{{ page_num }}</a>
            {% else %}
                <a href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}" class="btn btn-outline-info mb-4">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
{% endblock %}